Feature/rental controller
FabioSVBBD/RentalApp pull request #26
Opened 2022-04-19 13:34 UTC by zaeemasvatbbd

2022-04-19 15:35 UTC, Carmen-JvR requested changes

2022-04-19 15:35 UTC, Carmen-JvR commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +        //this.rentals = rentals;
Remove Comments

2022-04-19 15:35 UTC, Carmen-JvR commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +    //private RentalRepository rentals;
Remove Comments

2022-04-19 15:35 UTC, Carmen-JvR commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +//        rentalService.updateRental(rental);
Same here

2022-04-19 15:35 UTC, Carmen-JvR commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +//            return ResponseEntity.badRequest().build();
...

2022-04-20 11:36 UTC, luslindo approved these changes

2022-04-20 11:37 UTC, JustinPerumalBBD submitted a review, later dismissed

2022-04-20 11:50 UTC, FabioSVBBD requested changes

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/EmployeeController.java
>  		 }else {
Guard clause, can remove else block since return in above if

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/PaymentMethodController.java
> +@RequestMapping("rental-app/api/payment-method")
```suggestion
@RequestMapping("rental-app/api/payment-methods")
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/PaymentMethodController.java
> +    @GetMapping("get-payment-methods")
in light of above suggestions

```suggestion
    @GetMapping("")
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/PaymentMethodController.java
> +    @GetMapping("{id}/get-payment-by-id")
```suggestion
    @GetMapping("{id}")
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +        else if (employee != null) return ResponseEntity.ok(rentalRepository.findByEmployee(employee));
```suggestion
        if (employee != null) return ResponseEntity.ok(rentalRepository.findByEmployee(employee));
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +        else if (vehicle != null) return ResponseEntity.ok(rentalRepository.findByVehicle(vehicle));
```suggestion
        if (vehicle != null) return ResponseEntity.ok(rentalRepository.findByVehicle(vehicle));
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +        else return ResponseEntity.ok(rentalRepository.findAll());
```suggestion
        
        return ResponseEntity.ok(rentalRepository.findAll());
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +    @PostMapping("add-rental")
```suggestion
    @PostMapping("")
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +    @PatchMapping("{id}/update-rental")
```suggestion
    @PatchMapping("{id}")
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +    @GetMapping("{id}/get-total-cost")
```suggestion
    @GetMapping("{id}/total-cost")
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +    @GetMapping("{id}/get-rental-cost")
```suggestion
    @GetMapping("{id}/rental-cost")
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +    @PutMapping("{id}/make-payment")
```suggestion
    @PutMapping("{id}/pay")
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/RentalController.java
> +    @PostMapping("{id}/add-rental-review")
```suggestion
    @PostMapping("{id}/review")
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/ReviewController.java
> +    @GetMapping("view-top-reviews")
```suggestion
    @GetMapping("top")
```

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/ReviewController.java
> +    @GetMapping("view-reviews-by-date")
see if you can integrate this with optional parameters in the getReviews function

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/StatusController.java
> +    @GetMapping("{statusID}/{status}/update-status")
This is a get, shouldn't be mutating with gets

2022-04-20 11:50 UTC, FabioSVBBD commented on src/main/java/com/rental/rentalApp/controller/StatusController.java
> +    @GetMapping("{status}/get-status")
```suggestion
    @GetMapping("{status}")

```

2022-04-20 13:23 UTC, Carmen-JvR approved these changes

2022-04-20 13:24 UTC, luslindo approved these changes

2022-04-20 13:45 UTC, merged