Feature/populate tables
FabioSVBBD/RentalApp pull request #7
Opened 2022-04-08 14:40 UTC by zaeemasvatbbd

2022-04-08 15:13 UTC, FabioSVBBD commented on data/scripts/PopulateTables.sql
> +INSERT INTO [Vehicle]([VIN], [BrandID], [ModelID], [VehicleTypeID], [ColorID], [NumSeats], [DayRate], [HourlyRate], [YearPurchased], [LastService], [Transmission], [Mileage], [DepositAmount], [Availa
You're still using VIN here, please make sure this runs before committing

2022-04-08 15:14 UTC, FabioSVBBD requested changes
Make sure it runs fine on your side with no errors please

2022-04-08 15:18 UTC, zaeemasvatbbd commented on data/scripts/PopulateTables.sql
> +INSERT INTO [Vehicle]([VIN], [BrandID], [ModelID], [VehicleTypeID], [ColorID], [NumSeats], [DayRate], [HourlyRate], [YearPurchased], [LastService], [Transmission], [Mileage], [DepositAmount], [Availa
Oh so we've kept the VIN column in, it's just no longer a primary key. So we have to insert those values ourselves basically. I've tested it and can confirm that it runs.

2022-04-09 10:22 UTC, Carmen-JvR approved these changes

2022-04-09 10:40 UTC, FabioSVBBD approved these changes

2022-04-09 12:05 UTC, merged